services:
    metamodels.attribute_color.factory:
        class: MetaModels\Attribute\Color\AttributeTypeFactory
        arguments:
            - '@database_connection'
            - '@metamodels.table_manipulator'
            - '@event_dispatcher'
        tags:
          - { name: metamodels.attribute_factory }
