services:
    metamodels.attribute_color.factory:
        class: MetaModels\AttributeColorBundle\Attribute\AttributeTypeFactory
        arguments:
            - '@database_connection'
            - '@metamodels.table_manipulator'
        tags:
          - { name: metamodels.attribute_factory }
